- name: Install maven and Docker for CEP1
  hosts: webserver
  become: true
  become_user: root
  tasks:
  - name: Install maven on the worker nodes
    package: name={{item}} state=present
    loop:
     - maven
     - docker-ce
  - name: Start docker service
    service: name=docker state=started
